use enclava_common::image::ImageRef;
use enclava_common::types::{BootstrapPolicy, Durability, ResourceLimits, UnlockMode};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

pub const TENANT_INSTANCE_ANNOTATION: &str = "tenant.enclava.dev/instance";
pub const LEGACY_TENANT_INSTANCE_ANNOTATION: &str = "tenant.flowforge.sh/instance";

/// Complete specification for a confidential application deployment.
/// This is the sole input to the engine's manifest generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConfidentialApp {
    /// Stable UUID, used in KBS paths.
    pub app_id: Uuid,
    /// Human-readable name (unique within org).
    pub name: String,
    /// Kubernetes namespace (immutable after create).
    pub namespace: String,
    /// Stable identity for key derivation (immutable).
    /// OID-6: instance_id = "{tenant_id}-{app_id_short}".
    pub instance_id: String,
    /// Org identifier for identity hash computation (immutable).
    /// OID-6: tenant_id = org name.
    pub tenant_id: String,
    /// Hex SHA256 of the claim public key. Present for ALL apps:
    /// - Auto-unlock: platform generates the keypair and holds the private key
    /// - Password: user generates the keypair and holds the private key
    pub bootstrap_owner_pubkey_hash: String,
    /// SHA256(tenant_id:instance_id:pubkey_hash). Present for ALL apps.
    /// Used as the identity binding in KBS owner_resource_bindings Rego.
    pub tenant_instance_identity_hash: String,
    /// Kubernetes ServiceAccount name for this app.
    pub service_account: String,
    /// Optional Kubernetes image-pull secret attached to the ServiceAccount.
    /// The referenced Secret is created by the control plane in the tenant
    /// namespace and is only used by the kubelet for registry authentication.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image_pull_secret_name: Option<String>,
    /// Customer-controlled signer identity bound into KBS policy when present.
    pub signer_identity_subject: Option<String>,
    pub signer_identity_issuer: Option<String>,
    /// User's application containers.
    pub containers: Vec<Container>,
    /// Encrypted storage configuration (two volumes).
    pub storage: StorageSpec,
    /// How the app's storage is unlocked.
    pub unlock_mode: UnlockMode,
    /// Domain configuration.
    pub domain: DomainSpec,
    /// API's Ed25519 public key for config JWT verification (embedded in cc_init_data).
    pub api_signing_pubkey: String,
    /// API URL for config metadata sync.
    pub api_url: String,
    /// CPU and memory limits.
    pub resources: ResourceLimits,
    /// Attestation proxy and ingress sidecar configuration.
    pub attestation: AttestationConfig,
    /// Tenant egress posture. Default is restricted: no broad public internet
    /// egress, only platform-required routes and explicit FQDN allowlist rules.
    #[serde(default)]
    pub egress_mode: EgressMode,
    /// Additional IPv4 CIDRs excluded from `public_internet` egress. Operators
    /// use this to block cluster/node public ranges that are not covered by
    /// private RFC1918 exclusions.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub public_internet_egress_excluded_cidrs: Vec<String>,
    /// Per-app FQDN egress allowlist (Phase 11). Default: empty -> no
    /// FQDN rules emitted. Each rule is rendered as a Cilium `toFQDNs`
    /// egress entry restricted to the listed TCP ports.
    #[serde(default)]
    pub egress_allowlist: Vec<EgressRule>,
    /// Tenant public log encryption key selected by PaaS for this deployment.
    /// This is public metadata only. Tenant private decryption material must
    /// never be passed to CAP, enclava-init, Kubernetes, or GitOps.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub log_encryption: Option<LogEncryptionConfig>,
    /// Customer-signed descriptor/keyring values that must be carried in
    /// cc_init_data so enclava-init can fetch and verify workload artifacts.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workload_artifact_binding: Option<WorkloadArtifactBinding>,
    /// Kata agent policy generated by the pinned platform genpolicy release.
    /// When present this is the authoritative `policy.rego` body embedded in
    /// cc_init_data; the legacy local policy builder is only a fallback for
    /// unsigned/dev paths.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_agent_policy: Option<GeneratedAgentPolicy>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct WorkloadArtifactBinding {
    #[serde(with = "hex_bytes32")]
    pub descriptor_core_hash: [u8; 32],
    #[serde(with = "hex_bytes32")]
    pub descriptor_signing_pubkey: [u8; 32],
    #[serde(with = "hex_bytes32")]
    pub org_keyring_fingerprint: [u8; 32],
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct GeneratedAgentPolicy {
    pub policy_text: String,
    #[serde(with = "hex_bytes32")]
    pub policy_sha256: [u8; 32],
    pub genpolicy_version_pin: String,
}

mod hex_bytes32 {
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S: Serializer>(b: &[u8; 32], s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(&hex::encode(b))
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<[u8; 32], D::Error> {
        use serde::de::Error;
        let s = String::deserialize(d)?;
        let bytes = hex::decode(&s).map_err(D::Error::custom)?;
        bytes.try_into().map_err(|_| D::Error::custom("len != 32"))
    }
}

/// One world-egress allowance. Hosts must validate as FQDNs (see
/// `enclava_common::validate::validate_fqdn`); ports are TCP only.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct EgressRule {
    pub host: String,
    pub ports: Vec<u16>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LogEncryptionConfig {
    pub algorithm: String,
    pub key_id: String,
    pub public_key_base64url: String,
    pub public_key_sha256: String,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "snake_case")]
pub enum EgressMode {
    #[default]
    Restricted,
    PublicInternet,
}

impl EgressMode {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Restricted => "restricted",
            Self::PublicInternet => "public_internet",
        }
    }
}

impl std::str::FromStr for EgressMode {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value.trim().to_ascii_lowercase().as_str() {
            "" | "restricted" => Ok(Self::Restricted),
            "public_internet" | "public-internet" => Ok(Self::PublicInternet),
            other => Err(format!(
                "invalid egress_mode {other:?}; expected restricted or public_internet"
            )),
        }
    }
}

/// Tenant Caddy TLS issuer mode.
///
/// Production uses ACME TLS-ALPN-01. Internal mode is intended for fast
/// development/live-smoke loops where clients already run with `curl -k` or
/// CAP's staging/insecure TLS mode and external ACME would only add latency.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "kebab-case")]
pub enum CaddyTlsMode {
    #[default]
    Acme,
    Dns01Broker,
    Internal,
}

impl CaddyTlsMode {
    pub fn is_default(mode: &Self) -> bool {
        *mode == Self::Acme
    }
}

impl std::str::FromStr for CaddyTlsMode {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value.trim().to_ascii_lowercase().as_str() {
            "" | "acme" => Ok(Self::Acme),
            "dns01-broker" | "dns-01-broker" | "broker" => Ok(Self::Dns01Broker),
            "internal" => Ok(Self::Internal),
            other => Err(format!(
                "invalid tenant Caddy TLS mode {other:?}; expected acme, dns01-broker, or internal"
            )),
        }
    }
}

/// Attestation proxy configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttestationConfig {
    /// Attestation proxy image reference (digest-pinned).
    pub proxy_image: ImageRef,
    /// Caddy tenant-ingress image reference (digest-pinned).
    pub caddy_image: ImageRef,
    /// ACME directory URL used by tenant Caddy for TLS-ALPN-01 issuance.
    #[serde(default = "default_acme_ca_url")]
    pub acme_ca_url: String,
    /// TLS issuer mode for tenant Caddy.
    #[serde(default, skip_serializing_if = "CaddyTlsMode::is_default")]
    pub caddy_tls_mode: CaddyTlsMode,
    /// Enables in-TEE Trustee policy verification once the Trustee workload
    /// policy-read and CAP workload-artifact endpoints are deployed.
    #[serde(default)]
    pub trustee_policy_read_available: bool,
    /// CAP API workload-attested artifact endpoint reachable from the workload.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workload_artifacts_url: Option<String>,
    /// CAP API workload-attested DNS-01 certificate broker endpoint. In
    /// broker mode, enclava-init generates the tenant TLS key inside the TEE,
    /// submits a CSR over this endpoint, and writes the returned chain into
    /// Caddy's shared runtime directory.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tls_certificate_broker_url: Option<String>,
    /// Trustee workload-attested active policy body endpoint for this platform.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trustee_policy_url: Option<String>,
    /// Local workload artifact bundle JSON to mount into enclava-init when
    /// direct in-TEE egress to CAP is unavailable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub local_workload_artifacts_json: Option<String>,
    /// Local policy artifact JSON to mount into enclava-init when direct
    /// in-TEE egress to Trustee is unavailable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub local_trustee_policy_json: Option<String>,
    /// Platform Ed25519 public key for Trustee policy artifacts, hex encoded.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub platform_trustee_policy_pubkey_hex: Option<String>,
    /// Signing-service Ed25519 public key for descriptor/keyring authorization,
    /// hex encoded.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signing_service_pubkey_hex: Option<String>,
}

pub fn default_acme_ca_url() -> String {
    "https://acme-v02.api.letsencrypt.org/directory".to_string()
}

/// A user-defined container in the app pod.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Container {
    /// Container name (e.g., "web", "redis").
    pub name: String,
    /// OCI image reference. Must have digest for deployment (enforced at validation time).
    pub image: ImageRef,
    /// Port the container listens on.
    pub port: Option<u16>,
    /// Override command.
    pub command: Option<Vec<String>>,
    /// Non-secret environment variables.
    pub env: std::collections::HashMap<String, String>,
    /// Paths to bind-mount from the app-data LUKS volume.
    pub storage_paths: Vec<String>,
    /// Runtime security profile for the workload container. The default
    /// restricted profile runs the container as the workload user. Platform
    /// templates that need a root-owned supervisor or tenant sudo opt into a
    /// named profile.
    #[serde(default, skip_serializing_if = "WorkloadSecurityProfile::is_default")]
    pub workload_security_profile: WorkloadSecurityProfile,
    /// Whether this is the primary container (gets domain routing).
    pub is_primary: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "kebab-case")]
pub enum WorkloadSecurityProfile {
    #[default]
    Restricted,
    PlatformManagedSshRelay,
    RootfulSudo,
}

impl WorkloadSecurityProfile {
    pub fn is_default(profile: &Self) -> bool {
        *profile == Self::Restricted
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Restricted => "restricted",
            Self::PlatformManagedSshRelay => "platform-managed-ssh-relay",
            Self::RootfulSudo => "rootful-sudo",
        }
    }
}

impl std::str::FromStr for WorkloadSecurityProfile {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value.trim() {
            "" | "restricted" => Ok(Self::Restricted),
            "platform-managed-ssh-relay" => Ok(Self::PlatformManagedSshRelay),
            "rootful-sudo" => Ok(Self::RootfulSudo),
            other => Err(format!(
                "unsupported workload_security_profile {other:?}; expected restricted, platform-managed-ssh-relay, or rootful-sudo"
            )),
        }
    }
}

/// Two-volume storage specification.
///
/// App data is owner-seed backed. TLS data keeps the legacy KBS seed model so
/// Caddy can start with persisted certificates before app-data is claimed or
/// unlocked.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StorageSpec {
    pub app_data: VolumeSpec,
    pub tls_data: VolumeSpec,
}

impl StorageSpec {
    /// Create default storage spec with given sizes.
    pub fn new(app_data_size: &str, tls_data_size: &str) -> Self {
        Self {
            app_data: VolumeSpec {
                size: app_data_size.to_string(),
                device_path: "/dev/csi0".to_string(),
                mount_path: "/data".to_string(),
                durability: Durability::DurableState,
                bootstrap_policy: BootstrapPolicy::FirstBootOnly,
                bind_mounts: Vec::new(),
            },
            tls_data: VolumeSpec {
                size: tls_data_size.to_string(),
                device_path: "/dev/csi1".to_string(),
                mount_path: "/tls-data".to_string(),
                durability: Durability::DisposableState,
                bootstrap_policy: BootstrapPolicy::AllowReinit,
                bind_mounts: Vec::new(),
            },
        }
    }
}

/// Configuration for a single LUKS-encrypted block volume.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VolumeSpec {
    /// Volume size (e.g., "10Gi").
    pub size: String,
    /// Block device path inside the container (e.g., "/dev/csi0").
    pub device_path: String,
    /// Mount point for the decrypted filesystem (e.g., "/data").
    pub mount_path: String,
    /// Durability class.
    pub durability: Durability,
    /// Bootstrap policy for LUKS initialization.
    pub bootstrap_policy: BootstrapPolicy,
    /// Bind mounts from subdirectories to container paths.
    pub bind_mounts: Vec<BindMount>,
}

/// A bind mount from a LUKS volume subdirectory to a container path.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BindMount {
    /// Source path within the LUKS volume (e.g., "/data/postgresql").
    pub source: String,
    /// Destination path in the container (e.g., "/var/lib/postgresql/data").
    pub destination: String,
}

/// Domain configuration for an app. Per D1 (two-hostname model) every app
/// has both a user-facing app hostname and a TEE-facing hostname.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DomainSpec {
    /// App hostname `<app>.<orgSlug>.<platform_domain>`.
    pub platform_domain: String,
    /// TEE hostname `<app>.<orgSlug>.<tee_domain_suffix>`.
    #[serde(default)]
    pub tee_domain: String,
    /// Optional custom domain (e.g., "app.example.com").
    pub custom_domain: Option<String>,
}

impl ConfidentialApp {
    /// Returns the primary container (the one that gets domain routing).
    pub fn primary_container(&self) -> Option<&Container> {
        self.containers.iter().find(|c| c.is_primary)
    }

    /// Returns the app's primary domain (custom if set, platform otherwise).
    pub fn primary_domain(&self) -> &str {
        self.domain
            .custom_domain
            .as_deref()
            .unwrap_or(&self.domain.platform_domain)
    }

    /// KBS owner ciphertext path for this app.
    /// E.g., "default/{namespace}-{name}-owner/seed-encrypted"
    pub fn owner_resource_path(&self) -> String {
        format!("default/{}/seed-encrypted", self.owner_resource_type())
    }

    /// Stable owner-resource instance name used by the attestation proxy.
    ///
    /// The live Trustee policy derives owner resource access from the attested
    /// Kubernetes namespace and the tenant instance annotation, so CAP uses the
    /// namespace and app name for the KBS owner path.
    pub fn owner_instance_id(&self) -> String {
        format!("{}-{}", self.namespace, self.name)
    }

    /// KBS owner resource type for `owner_resource_bindings`.
    pub fn owner_resource_type(&self) -> String {
        format!("{}-owner", self.owner_instance_id())
    }

    /// KBS TLS resource path used by tenant-ingress Caddy.
    pub fn tls_resource_path(&self) -> String {
        format!("default/{}/workload-secret-seed", self.tls_resource_type())
    }

    /// KBS TLS resource type for generic `resource_bindings`.
    pub fn tls_resource_type(&self) -> String {
        format!("{}-tls", self.owner_instance_id())
    }
}
