[package]
name = "enclava-verifier"
version = "0.1.0"
edition.workspace = true

[dependencies]
base64 = { workspace = true }
chrono = { workspace = true }
ed25519-dalek = { version = "2", default-features = false, features = ["alloc"] }
enclava-common = { path = "../enclava-common", default-features = false, features = ["descriptor"] }
hex = { workspace = true }
p384 = { workspace = true }
p256 = { version = "0.13", default-features = false, features = ["alloc", "ecdsa", "pkcs8"] }
num-bigint = { workspace = true }
pkcs1 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
uuid = { version = "1", default-features = false, features = ["serde"] }
x509-cert = { workspace = true }

[dev-dependencies]
base64 = { workspace = true }
